In [2]:
import pandas as pd

In [3]:
df=pd.read_csv('WELFake_Dataset.csv')

In [4]:
df.head()

Unnamed: 0                                              title  \
0           0  LAW ENFORCEMENT ON HIGH ALERT Following Threat...   
1           1                                                NaN   
2           2  UNBELIEVABLE! OBAMA’S ATTORNEY GENERAL SAYS MO...   
3           3  Bobby Jindal, raised Hindu, uses story of Chri...   
4           4  SATAN 2: Russia unvelis an image of its terrif...   

                                                text  label  
0  No comment is expected from Barack Obama Membe...      1  
1     Did they post their votes for Hillary already?      1  
2   Now, most of the demonstrators gathered last ...      1  
3  A dozen politically active pastors came here f...      0  
4  The RS-28 Sarmat missile, dubbed Satan 2, will...      1

In [5]:
df=df.dropna()

In [6]:
df.head()

Unnamed: 0                                              title  \
0           0  LAW ENFORCEMENT ON HIGH ALERT Following Threat...   
2           2  UNBELIEVABLE! OBAMA’S ATTORNEY GENERAL SAYS MO...   
3           3  Bobby Jindal, raised Hindu, uses story of Chri...   
4           4  SATAN 2: Russia unvelis an image of its terrif...   
5           5  About Time! Christian Group Sues Amazon and SP...   

                                                text  label  
0  No comment is expected from Barack Obama Membe...      1  
2   Now, most of the demonstrators gathered last ...      1  
3  A dozen politically active pastors came here f...      0  
4  The RS-28 Sarmat missile, dubbed Satan 2, will...      1  
5  All we can say on this one is it s about time ...      1

In [12]:
df["title"]

0        LAW ENFORCEMENT ON HIGH ALERT Following Threat...
2        UNBELIEVABLE! OBAMA’S ATTORNEY GENERAL SAYS MO...
3        Bobby Jindal, raised Hindu, uses story of Chri...
4        SATAN 2: Russia unvelis an image of its terrif...
5        About Time! Christian Group Sues Amazon and SP...
                               ...                        
72129    Russians steal research on Trump in hack of U....
72130     WATCH: Giuliani Demands That Democrats Apolog...
72131    Migrants Refuse To Leave Train At Refugee Camp...
72132    Trump tussle gives unpopular Mexican leader mu...
72133    Goldman Sachs Endorses Hillary Clinton For Pre...
Name: title, Length: 71537, dtype: object

In [7]:
X=df.drop('label',axis=1)

In [8]:
y=df['label']

In [9]:
X.shape

(71537, 3)

In [10]:
y.shape

(71537,)

In [12]:
import tensorflow as tf

In [13]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense

In [14]:
#Vocabulary size
voc_size=5000

In [20]:
#One hot representation
message=X.copy()
message['title'][3]

'Bobby Jindal, raised Hindu, uses story of Christian conversion to woo evangelicals for potential 2016 bid'

In [22]:
message.reset_index(inplace=True)

In [23]:
import nltk
import re
from nltk.corpus import stopwords

In [24]:
 nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [27]:
### Dataset Preprocessing
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()
corpus = []
for i in range(0, len(message)):
    review = re.sub('[^a-zA-Z]', ' ', message['title'][i])
    review = review.lower()
    review = review.split()

    review = [ps.stem(word) for word in review if not word in stopwords.words('english')]
    review = ' '.join(review)
    corpus.append(review)

In [28]:
corpus

['law enforc high alert follow threat cop white blacklivesmatt fyf terrorist video',
 'unbeliev obama attorney gener say charlott rioter peac protest home state north carolina video',
 'bobbi jindal rais hindu use stori christian convers woo evangel potenti bid',
 'satan russia unv imag terrifi new supernuk western world take notic',
 'time christian group sue amazon splc design hate group',
 'dr ben carson target ir never audit spoke nation prayer breakfast',
 'hous intel chair trump russia fake stori evid anyth video',
 'sport bar owner ban nfl game show true american sport like speak rural america video',
 'latest pipelin leak underscor danger dakota access pipelin',
 'gop senat smack punchabl alt right nazi internet',
 'may brexit offer would hurt cost eu citizen eu parliament',
 'schumer call trump appoint offici overse puerto rico relief',
 'watch hilari ad call question health age clinton crime famili boss',
 'chang expect espn polit agenda despit huge subscrib declin breitbart'

In [29]:
onehot_repr=[one_hot(words,voc_size)for words in corpus]
onehot_repr

[[2507, 4848, 1323, 4550, 4996, 85, 1637, 4157, 3974, 4100, 3492, 1161],
 [2662,
  301,
  618,
  1762,
  3091,
  593,
  3576,
  1556,
  283,
  3749,
  2716,
  11,
  4005,
  1161],
 [1583, 2330, 2805, 3105, 1889, 470, 92, 4323, 3921, 4349, 1691, 316],
 [942, 2086, 3342, 3752, 1345, 2160, 3481, 3320, 1033, 1896, 3960],
 [252, 92, 4861, 409, 4428, 4029, 2075, 154, 4861],
 [1738, 4461, 3181, 1754, 3486, 1821, 275, 2434, 915, 1561, 1120],
 [2458, 2732, 3968, 2585, 2086, 1076, 470, 318, 3142, 1161],
 [4098,
  2952,
  3191,
  2706,
  72,
  2530,
  2949,
  4593,
  595,
  4098,
  2500,
  3511,
  376,
  3446,
  1161],
 [4235, 1394, 3949, 2933, 2310, 1697, 1725, 1394],
 [952, 3882, 3068, 64, 315, 455, 461, 936],
 [1827, 2457, 527, 2464, 990, 4192, 2486, 2401, 2486, 4588],
 [790, 4707, 2585, 4, 3132, 1630, 540, 4916, 762],
 [2871, 4509, 2843, 4707, 4914, 1958, 977, 1884, 4115, 1911, 3962],
 [1678, 2356, 151, 3169, 3078, 3802, 1817, 4093, 867, 3538],
 [962, 4285, 1213, 1715, 1191, 2458, 4364],
 [11

In [31]:
#Embedding Representation
sent_length=20
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0 ... 4100 3492 1161]
 [   0    0    0 ...   11 4005 1161]
 [   0    0    0 ... 4349 1691  316]
 ...
 [   0    0    0 ... 1275  663 3366]
 [   0    0    0 ... 1922 4410 4007]
 [   0    0    0 ... 2555 1884 1174]]


In [32]:
embedded_docs[0]

array([   0,    0,    0,    0,    0,    0,    0,    0, 2507, 4848, 1323,
       4550, 4996,   85, 1637, 4157, 3974, 4100, 3492, 1161], dtype=int32)

In [78]:
## Creating model
embedding_vector_features=40
model=Sequential()
model.add(Embedding(voc_size,embedding_vector_features,input_length=sent_length))
model.add(LSTM(100))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
print(model.summary())

Model: "sequential_7"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_7 (Embedding)     (None, 20, 40)            200000    
                                                                 
 lstm_6 (LSTM)               (None, 100)               56400     
                                                                 
 dense_7 (Dense)             (None, 1)                 101       
                                                                 
Total params: 256501 (1001.96 KB)
Trainable params: 256501 (1001.96 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________
None


In [63]:
len(embedded_docs),y.shape

(71537, (71537,))

In [79]:
import numpy as np
X_final=np.array(embedded_docs)
y_final=np.array(y)

In [80]:
X_final.shape,y_final.shape

((71537, 20), (71537,))

In [81]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_final, y_final, test_size=0.33, random_state=42)

In [82]:
#Model training
model.fit(X_train,y_train,validation_data=(X_test,y_test),epochs=5,batch_size=70)

Epoch 1/5
685/685 [==============================] - 36s 50ms/step - loss: 0.3292 - accuracy: 0.8522 - val_loss: 0.2667 - val_accuracy: 0.8870
Epoch 2/5
685/685 [==============================] - 29s 43ms/step - loss: 0.2271 - accuracy: 0.9064 - val_loss: 0.2561 - val_accuracy: 0.8927
Epoch 3/5
685/685 [==============================] - 29s 42ms/step - loss: 0.1953 - accuracy: 0.9217 - val_loss: 0.2590 - val_accuracy: 0.8938
Epoch 4/5
685/685 [==============================] - 30s 44ms/step - loss: 0.1704 - accuracy: 0.9323 - val_loss: 0.2579 - val_accuracy: 0.8945
Epoch 5/5
685/685 [==============================] - 30s 44ms/step - loss: 0.1455 - accuracy: 0.9432 - val_loss: 0.2796 - val_accuracy: 0.8914


In [103]:
y_pred_probs = model.predict(X_test)
threshold = 0.5  # You can adjust this threshold based on your requirements
y_pred_classes = (y_pred_probs > threshold).astype(int)


738/738 [==============================] - 5s 7ms/step


In [105]:
y_pred_classes

array([[1],
       [0],
       [0],
       ...,
       [1],
       [1],
       [0]])

In [106]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test,y_pred_classes)

array([[10095,  1598],
       [  965, 10950]])

In [107]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred_classes)

0.8914351067434768

In [108]:
## Creating model using bidirectional LSTM
from tensorflow.keras.layers import Bidirectional
from tensorflow.keras.layers import Dropout
embedding_vector_features=40
model1=Sequential()
model1.add(Embedding(voc_size,embedding_vector_features,input_length=sent_length))
model1.add(Bidirectional(LSTM(100)))
model1.add(Dropout(0.3))
model1.add(Dense(1,activation='sigmoid'))
model1.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
print(model1.summary())

Model: "sequential_8"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_8 (Embedding)     (None, 20, 40)            200000    
                                                                 
 bidirectional (Bidirection  (None, 200)               112800    
 al)                                                             
                                                                 
 dropout_2 (Dropout)         (None, 200)               0         
                                                                 
 dense_8 (Dense)             (None, 1)                 201       
                                                                 
Total params: 313001 (1.19 MB)
Trainable params: 313001 (1.19 MB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________
None


In [109]:
import numpy as np
X_final=np.array(embedded_docs)
y_final=np.array(y)

In [110]:

X_final.shape,y_final.shape

((71537, 20), (71537,))

In [111]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_final, y_final, test_size=0.33, random_state=42)

In [112]:
model1.fit(X_train,y_train,validation_data=(X_test,y_test),epochs=10,batch_size=64)

Epoch 1/10
749/749 [==============================] - 60s 75ms/step - loss: 0.3155 - accuracy: 0.8574 - val_loss: 0.2602 - val_accuracy: 0.8922
Epoch 2/10
749/749 [==============================] - 51s 68ms/step - loss: 0.2210 - accuracy: 0.9100 - val_loss: 0.2657 - val_accuracy: 0.8896
Epoch 3/10
749/749 [==============================] - 50s 67ms/step - loss: 0.1879 - accuracy: 0.9244 - val_loss: 0.2689 - val_accuracy: 0.8932
Epoch 4/10
749/749 [==============================] - 48s 64ms/step - loss: 0.1600 - accuracy: 0.9374 - val_loss: 0.2715 - val_accuracy: 0.8949
Epoch 5/10
749/749 [==============================] - 48s 64ms/step - loss: 0.1375 - accuracy: 0.9461 - val_loss: 0.3009 - val_accuracy: 0.8888
Epoch 6/10
749/749 [==============================] - 53s 71ms/step - loss: 0.1144 - accuracy: 0.9551 - val_loss: 0.3290 - val_accuracy: 0.8928
Epoch 7/10
749/749 [==============================] - 52s 69ms/step - loss: 0.0943 - accuracy: 0.9638 - val_loss: 0.3439 - val_accuracy:

In [113]:
y_pred_probs = model.predict(X_test)
threshold = 0.5  # You can adjust this threshold based on your requirements
y_pred_classes = (y_pred_probs > threshold).astype(int)

738/738 [==============================] - 5s 6ms/step


In [114]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test,y_pred_classes)

array([[10095,  1598],
       [  965, 10950]])

In [115]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred_classes)

0.8914351067434768