In [3]:
#Word embedding techiques using embedding layer in keras

##tensorflow >2.0
from tensorflow.keras.preprocessing.text import one_hot

In [4]:

### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [5]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [6]:

### Vocabulary size
voc_size=10000

In [7]:
onehot_repr=[one_hot(words,voc_size)for words in sent]
print(onehot_repr)

[[399, 5446, 31, 8525], [399, 5446, 31, 8912], [399, 1995, 31, 5560], [4952, 813, 2264, 9787, 1595], [4952, 813, 2264, 9787, 2154], [2603, 399, 2547, 31, 5593], [5354, 3031, 748, 9787]]


In [8]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [9]:

import numpy as np

In [10]:
sent_length=8
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0  399 5446   31 8525]
 [   0    0    0    0  399 5446   31 8912]
 [   0    0    0    0  399 1995   31 5560]
 [   0    0    0 4952  813 2264 9787 1595]
 [   0    0    0 4952  813 2264 9787 2154]
 [   0    0    0 2603  399 2547   31 5593]
 [   0    0    0    0 5354 3031  748 9787]]


In [11]:
dim=10

In [12]:
model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')

In [13]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [14]:
print(model.predict(embedded_docs))

1/1 [==============================] - 0s 122ms/step
[[[ 0.0313968  -0.04165169 -0.01239429 -0.02766806 -0.02163004
   -0.0497375   0.0198761  -0.01060302  0.02643849  0.02874804]
  [ 0.0313968  -0.04165169 -0.01239429 -0.02766806 -0.02163004
   -0.0497375   0.0198761  -0.01060302  0.02643849  0.02874804]
  [ 0.0313968  -0.04165169 -0.01239429 -0.02766806 -0.02163004
   -0.0497375   0.0198761  -0.01060302  0.02643849  0.02874804]
  [ 0.0313968  -0.04165169 -0.01239429 -0.02766806 -0.02163004
   -0.0497375   0.0198761  -0.01060302  0.02643849  0.02874804]
  [-0.01498128 -0.0333035  -0.045428    0.01436834 -0.00851786
    0.03106973 -0.03727338  0.03479994  0.02657324  0.03039766]
  [-0.04025874  0.04863061  0.00153451 -0.00662677  0.01473567
   -0.04843055  0.02158512 -0.00288711 -0.0130429  -0.03490334]
  [ 0.02421329  0.00248605  0.02433877  0.018424    0.02787227
    0.00829569  0.01063137  0.01310905 -0.03691376 -0.01011391]
  [-0.00722941  0.04750812  0.03023789  0.0065897  -0.0409

In [15]:
embedded_docs[0]

array([   0,    0,    0,    0,  399, 5446,   31, 8525], dtype=int32)

In [17]:
print(model.predict(embedded_docs)[0])

1/1 [==============================] - 0s 14ms/step
[[ 0.0313968  -0.04165169 -0.01239429 -0.02766806 -0.02163004 -0.0497375
   0.0198761  -0.01060302  0.02643849  0.02874804]
 [ 0.0313968  -0.04165169 -0.01239429 -0.02766806 -0.02163004 -0.0497375
   0.0198761  -0.01060302  0.02643849  0.02874804]
 [ 0.0313968  -0.04165169 -0.01239429 -0.02766806 -0.02163004 -0.0497375
   0.0198761  -0.01060302  0.02643849  0.02874804]
 [ 0.0313968  -0.04165169 -0.01239429 -0.02766806 -0.02163004 -0.0497375
   0.0198761  -0.01060302  0.02643849  0.02874804]
 [-0.01498128 -0.0333035  -0.045428    0.01436834 -0.00851786  0.03106973
  -0.03727338  0.03479994  0.02657324  0.03039766]
 [-0.04025874  0.04863061  0.00153451 -0.00662677  0.01473567 -0.04843055
   0.02158512 -0.00288711 -0.0130429  -0.03490334]
 [ 0.02421329  0.00248605  0.02433877  0.018424    0.02787227  0.00829569
   0.01063137  0.01310905 -0.03691376 -0.01011391]
 [-0.00722941  0.04750812  0.03023789  0.0065897  -0.04098574 -0.01407392
  -